version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../infrastructure/docker/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
      - ./backend/staticfiles:/app/staticfiles
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://hireiq_user:hireiq_password@db:5432/hireiq_db
    depends_on:
      - db
    networks:
      - hireiq_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - hireiq_network

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=hireiq_db
      - POSTGRES_USER=hireiq_user
      - POSTGRES_PASSWORD=hireiq_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - hireiq_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infrastructure/docker/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/staticfiles:/var/www/static
      - ./backend/media:/var/www/media
    depends_on:
      - backend
      - frontend
    networks:
      - hireiq_network

volumes:
  postgres_data:

networks:
  hireiq_network:
    driver: bridge 